################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../application_properties.c \
../cmu.c \
../gatt_db.c \
../gpio.c \
../init_app.c \
../init_board.c \
../init_mcu.c \
../letimer_sleep.c \
../main.c \
../pti.c \
../temperature_i2c.c 

OBJS += \
./application_properties.o \
./cmu.o \
./gatt_db.o \
./gpio.o \
./init_app.o \
./init_board.o \
./init_mcu.o \
./letimer_sleep.o \
./main.o \
./pti.o \
./temperature_i2c.o 

C_DEPS += \
./application_properties.d \
./cmu.d \
./gatt_db.d \
./gpio.d \
./init_app.d \
./init_board.d \
./init_mcu.d \
./letimer_sleep.d \
./main.d \
./pti.d \
./temperature_i2c.d 


# Each subdirectory must supply rules for building sources it contributes
application_properties.o: ../application_properties.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__STACK_SIZE=0x800' '-D__HEAP_SIZE=0xD00' '-DHAL_CONFIG=1' '-DEFR32BG1B232F256GM56=1' -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\sleep\src" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emlib\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\hardware\kit\common\halconfig" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\protocol\bluetooth_2.7\ble_stack\inc\common" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\sleep\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\CMSIS\Include" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\hardware\kit\common\bsp" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\hardware\kit\common\drivers" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\radio\rail_lib\chip\efr32" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\hardware\kit\EFR32BG1_BRD4302A\config" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\uartdrv\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\halconfig\inc\hal-config" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emlib\src" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\gpiointerrupt\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\app\bluetooth_2.7\common\stack_bridge" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\Device\SiliconLabs\EFR32BG1B\Source" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\tempdrv\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\bootloader\api" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\radio\rail_lib\common" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\protocol\bluetooth_2.7\ble_stack\inc\soc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\tempdrv\src" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\common\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"application_properties.d" -MT"application_properties.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

cmu.o: ../cmu.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__STACK_SIZE=0x800' '-D__HEAP_SIZE=0xD00' '-DHAL_CONFIG=1' '-DEFR32BG1B232F256GM56=1' -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\sleep\src" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emlib\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\hardware\kit\common\halconfig" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\protocol\bluetooth_2.7\ble_stack\inc\common" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\sleep\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\CMSIS\Include" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\hardware\kit\common\bsp" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\hardware\kit\common\drivers" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\radio\rail_lib\chip\efr32" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\hardware\kit\EFR32BG1_BRD4302A\config" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\uartdrv\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\halconfig\inc\hal-config" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emlib\src" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\gpiointerrupt\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\app\bluetooth_2.7\common\stack_bridge" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\Device\SiliconLabs\EFR32BG1B\Source" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\tempdrv\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\bootloader\api" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\radio\rail_lib\common" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\protocol\bluetooth_2.7\ble_stack\inc\soc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\tempdrv\src" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\common\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"cmu.d" -MT"cmu.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gatt_db.o: ../gatt_db.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__STACK_SIZE=0x800' '-D__HEAP_SIZE=0xD00' '-DHAL_CONFIG=1' '-DEFR32BG1B232F256GM56=1' -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\sleep\src" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emlib\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\hardware\kit\common\halconfig" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\protocol\bluetooth_2.7\ble_stack\inc\common" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\sleep\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\CMSIS\Include" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\hardware\kit\common\bsp" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\hardware\kit\common\drivers" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\radio\rail_lib\chip\efr32" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\hardware\kit\EFR32BG1_BRD4302A\config" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\uartdrv\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\halconfig\inc\hal-config" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emlib\src" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\gpiointerrupt\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\app\bluetooth_2.7\common\stack_bridge" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\Device\SiliconLabs\EFR32BG1B\Source" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\tempdrv\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\bootloader\api" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\radio\rail_lib\common" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\protocol\bluetooth_2.7\ble_stack\inc\soc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\tempdrv\src" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\common\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"gatt_db.d" -MT"gatt_db.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

gpio.o: ../gpio.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__STACK_SIZE=0x800' '-D__HEAP_SIZE=0xD00' '-DHAL_CONFIG=1' '-DEFR32BG1B232F256GM56=1' -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\sleep\src" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emlib\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\hardware\kit\common\halconfig" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\protocol\bluetooth_2.7\ble_stack\inc\common" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\sleep\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\CMSIS\Include" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\hardware\kit\common\bsp" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\hardware\kit\common\drivers" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\radio\rail_lib\chip\efr32" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\hardware\kit\EFR32BG1_BRD4302A\config" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\uartdrv\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\halconfig\inc\hal-config" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emlib\src" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\gpiointerrupt\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\app\bluetooth_2.7\common\stack_bridge" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\Device\SiliconLabs\EFR32BG1B\Source" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\tempdrv\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\bootloader\api" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\radio\rail_lib\common" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\protocol\bluetooth_2.7\ble_stack\inc\soc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\tempdrv\src" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\common\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"gpio.d" -MT"gpio.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

init_app.o: ../init_app.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__STACK_SIZE=0x800' '-D__HEAP_SIZE=0xD00' '-DHAL_CONFIG=1' '-DEFR32BG1B232F256GM56=1' -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\sleep\src" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emlib\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\hardware\kit\common\halconfig" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\protocol\bluetooth_2.7\ble_stack\inc\common" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\sleep\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\CMSIS\Include" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\hardware\kit\common\bsp" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\hardware\kit\common\drivers" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\radio\rail_lib\chip\efr32" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\hardware\kit\EFR32BG1_BRD4302A\config" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\uartdrv\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\halconfig\inc\hal-config" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emlib\src" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\gpiointerrupt\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\app\bluetooth_2.7\common\stack_bridge" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\Device\SiliconLabs\EFR32BG1B\Source" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\tempdrv\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\bootloader\api" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\radio\rail_lib\common" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\protocol\bluetooth_2.7\ble_stack\inc\soc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\tempdrv\src" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\common\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"init_app.d" -MT"init_app.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

init_board.o: ../init_board.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__STACK_SIZE=0x800' '-D__HEAP_SIZE=0xD00' '-DHAL_CONFIG=1' '-DEFR32BG1B232F256GM56=1' -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\sleep\src" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emlib\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\hardware\kit\common\halconfig" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\protocol\bluetooth_2.7\ble_stack\inc\common" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\sleep\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\CMSIS\Include" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\hardware\kit\common\bsp" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\hardware\kit\common\drivers" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\radio\rail_lib\chip\efr32" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\hardware\kit\EFR32BG1_BRD4302A\config" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\uartdrv\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\halconfig\inc\hal-config" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emlib\src" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\gpiointerrupt\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\app\bluetooth_2.7\common\stack_bridge" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\Device\SiliconLabs\EFR32BG1B\Source" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\tempdrv\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\bootloader\api" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\radio\rail_lib\common" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\protocol\bluetooth_2.7\ble_stack\inc\soc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\tempdrv\src" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\common\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"init_board.d" -MT"init_board.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

init_mcu.o: ../init_mcu.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__STACK_SIZE=0x800' '-D__HEAP_SIZE=0xD00' '-DHAL_CONFIG=1' '-DEFR32BG1B232F256GM56=1' -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\sleep\src" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emlib\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\hardware\kit\common\halconfig" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\protocol\bluetooth_2.7\ble_stack\inc\common" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\sleep\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\CMSIS\Include" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\hardware\kit\common\bsp" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\hardware\kit\common\drivers" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\radio\rail_lib\chip\efr32" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\hardware\kit\EFR32BG1_BRD4302A\config" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\uartdrv\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\halconfig\inc\hal-config" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emlib\src" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\gpiointerrupt\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\app\bluetooth_2.7\common\stack_bridge" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\Device\SiliconLabs\EFR32BG1B\Source" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\tempdrv\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\bootloader\api" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\radio\rail_lib\common" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\protocol\bluetooth_2.7\ble_stack\inc\soc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\tempdrv\src" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\common\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"init_mcu.d" -MT"init_mcu.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

letimer_sleep.o: ../letimer_sleep.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__STACK_SIZE=0x800' '-D__HEAP_SIZE=0xD00' '-DHAL_CONFIG=1' '-DEFR32BG1B232F256GM56=1' -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\sleep\src" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emlib\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\hardware\kit\common\halconfig" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\protocol\bluetooth_2.7\ble_stack\inc\common" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\sleep\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\CMSIS\Include" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\hardware\kit\common\bsp" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\hardware\kit\common\drivers" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\radio\rail_lib\chip\efr32" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\hardware\kit\EFR32BG1_BRD4302A\config" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\uartdrv\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\halconfig\inc\hal-config" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emlib\src" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\gpiointerrupt\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\app\bluetooth_2.7\common\stack_bridge" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\Device\SiliconLabs\EFR32BG1B\Source" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\tempdrv\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\bootloader\api" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\radio\rail_lib\common" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\protocol\bluetooth_2.7\ble_stack\inc\soc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\tempdrv\src" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\common\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"letimer_sleep.d" -MT"letimer_sleep.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

main.o: ../main.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__STACK_SIZE=0x800' '-D__HEAP_SIZE=0xD00' '-DHAL_CONFIG=1' '-DEFR32BG1B232F256GM56=1' -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\sleep\src" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emlib\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\hardware\kit\common\halconfig" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\protocol\bluetooth_2.7\ble_stack\inc\common" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\sleep\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\CMSIS\Include" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\hardware\kit\common\bsp" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\hardware\kit\common\drivers" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\radio\rail_lib\chip\efr32" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\hardware\kit\EFR32BG1_BRD4302A\config" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\uartdrv\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\halconfig\inc\hal-config" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emlib\src" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\gpiointerrupt\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\app\bluetooth_2.7\common\stack_bridge" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\Device\SiliconLabs\EFR32BG1B\Source" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\tempdrv\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\bootloader\api" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\radio\rail_lib\common" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\protocol\bluetooth_2.7\ble_stack\inc\soc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\tempdrv\src" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\common\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"main.d" -MT"main.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

pti.o: ../pti.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__STACK_SIZE=0x800' '-D__HEAP_SIZE=0xD00' '-DHAL_CONFIG=1' '-DEFR32BG1B232F256GM56=1' -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\sleep\src" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emlib\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\hardware\kit\common\halconfig" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\protocol\bluetooth_2.7\ble_stack\inc\common" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\sleep\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\CMSIS\Include" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\hardware\kit\common\bsp" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\hardware\kit\common\drivers" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\radio\rail_lib\chip\efr32" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\hardware\kit\EFR32BG1_BRD4302A\config" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\uartdrv\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\halconfig\inc\hal-config" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emlib\src" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\gpiointerrupt\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\app\bluetooth_2.7\common\stack_bridge" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\Device\SiliconLabs\EFR32BG1B\Source" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\tempdrv\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\bootloader\api" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\radio\rail_lib\common" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\protocol\bluetooth_2.7\ble_stack\inc\soc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\tempdrv\src" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\common\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"pti.d" -MT"pti.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

temperature_i2c.o: ../temperature_i2c.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU ARM C Compiler'
	arm-none-eabi-gcc -g -gdwarf-2 -mcpu=cortex-m4 -mthumb -std=c99 '-D__STACK_SIZE=0x800' '-D__HEAP_SIZE=0xD00' '-DHAL_CONFIG=1' '-DEFR32BG1B232F256GM56=1' -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\Device\SiliconLabs\EFR32BG1B\Include" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\sleep\src" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emlib\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\hardware\kit\common\halconfig" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\Device\SiliconLabs\EFR32BG1B\Source\GCC" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\protocol\bluetooth_2.7\ble_stack\inc\common" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\sleep\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\CMSIS\Include" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\hardware\kit\common\bsp" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\hardware\kit\common\drivers" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\radio\rail_lib\chip\efr32" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\hardware\kit\EFR32BG1_BRD4302A\config" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\uartdrv\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\halconfig\inc\hal-config" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emlib\src" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\gpiointerrupt\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\app\bluetooth_2.7\common\stack_bridge" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\Device\SiliconLabs\EFR32BG1B\Source" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\tempdrv\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\bootloader\api" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\radio\rail_lib\common" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\protocol\bluetooth_2.7\ble_stack\inc\soc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\tempdrv\src" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\emdrv\common\inc" -I"C:\SiliconLabs\SimplicityStudio\v4_3\Monish_Nene_OTA\platform\bootloader" -O2 -Wall -c -fmessage-length=0 -ffunction-sections -fdata-sections -mfpu=fpv4-sp-d16 -mfloat-abi=softfp -MMD -MP -MF"temperature_i2c.d" -MT"temperature_i2c.o" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


